version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - prometheus
      - loki
      - tempo
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=7d"
      - "--web.enable-remote-write-receiver"
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.4.1
    ports:
      - "3200:3200"
    volumes:
      - ./tempo-config.yaml:/etc/tempo/config.yaml
      - tempo-data:/data/tempo
    command: ["-config.file=/etc/tempo/config.yaml"]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - otel-collector
    environment:
      - OTEL_METRIC_EXPORT_INTERVAL=500
    ports:
      - "8080:8080"

volumes:
  grafana-data:
  loki-data:
  tempo-data:
  prometheus-data: